### ISSUE TITLE
Is there a reference paper for this project?

### ISSUE THREAD

**Issue by sheirving** [chunkyjasper/IAMhwr#1]
Fist of all, thankyou very much for shared this project !
Is there  a reference paper for the feature extraction? Thankyou.

**Comment by chunkyjasper** [comment]
[FYPreport-Chun-Chan.pdf](https://github.com/chunkyjasper/IAMhwr/files/4015515/FYPreport-Chun-Chan.pdf)

Here it is. I rushed the report for the deadline so the writing quality is so-so, there will be mistakes and things that don't make much sense. If you have any problem feel free to ask me.

For the feature extraction in particular, please ignore the cosine downsampling part, it was meant for another model configuration, I simply had no time to take it out of the current iteration for thesis submission.
